# Generated by Django 5.2.6 on 2025-10-31 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
